example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import show_wishlist, show_wishlist_ajax
from wishlist.views import show_xml
from wishlist.views import show_json 
from wishlist.views import show_json_by_id
from wishlist.views import register
from wishlist.views import login_user
from wishlist.views import logout_user
app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
   
    path('xml/', show_xml, name='show_xml'), 

    path('json/', show_json, name='show_json'),

    path('json/<int:id>', show_json_by_id, name='show_json_by_id'), #sesuaikan dengan nama fungsi yang dibuat

    path('register/', register, name='register'), 

    path('login/', login_user, name='login'),

    path('logout/', logout_user, name='logout'),
    path('ajax/', show_wishlist_ajax, name='logout'),
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
from django.shortcuts import render
from wishlist.models import BarangWishlist
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
# Create your views here.
data_barang_wishlist = BarangWishlist.objects.all()


@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    context = {
    'list_barang': data_barang_wishlist,
    'nama': 'Stelline',
    'last_login': request.COOKIES['last_login'],
}
    return render(request, "wishlist.html", context)
def show_xml(request):
    return HttpResponse(serializers.serialize("xml", data_barang_wishlist), content_type="application/xml")
def show_json(request):
    return HttpResponse(serializers.serialize("json", data_barang_wishlist), content_type="application/json")
def show_json_by_id(request,  id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")
def show_wishlist_ajax(request):
    return render(request, "wishlist_ajax.html")
def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a>

</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
<!doctype html>
<html lang="en">
    <nav class="navbar navbar-expand-lg bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#" style="color:lightgrey" >Stelline</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <button><a href="{% url 'wishlist:logout' %}">Logout</a></button>
              </li>
              
          </div>
        </div>
      </nav>
      
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <h2>Nama:{{nama}} </h2>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  </head>
  <style>
    table, th, td {
      border:2px solid black;
    }
</style>
  <body>
    <table  style="width:100%">
        <tr>
        <th style = "background-color: grey">Nama Barang</th>
        <th style = "background-color: grey">Harga Barang</th>
        <th style = "background-color: grey">Deskripsi</th>
        </tr>
    {% for barang in list_barang %}
        <tr>
            <th style = "background-color: lightgrey">{{barang.nama_barang}}</th>
            <th style = "background-color: lightgrey">{{barang.harga_barang}}</th>
            <th style = "background-color: lightgrey">{{barang.deskripsi}}</th>
        </tr>
    {% endfor %}
    </table>
    ...<h5>Sesi terakhir login: {{ last_login }}</h5>
    
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  </body>
</html>

wishlist/templates/wishlist_ajax.html
<!doctype html>
<html lang="en">
    <nav class="navbar navbar-expand-lg bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#" style="color:lightgrey" >Stelline</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <button><a href="{% url 'wishlist:logout' %}">Logout</a></button>
              </li>
              
          </div>
        </div>
      </nav>
      
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <h2>Nama:{{nama}} </h2>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  </head>
  <style>
    table, th, td {
      border:2px solid black;
    }
</style>
  <body>
    <table  style="width:100%">
        <tr>
        <th style = "background-color: grey">Nama Barang</th>
        <th style = "background-color: grey">Harga Barang</th>
        <th style = "background-color: grey">Deskripsi</th>
        </tr>
    {% for barang in list_barang %}
        <tr>
            <th style = "background-color: lightgrey">{{barang.nama_barang}}</th>
            <th style = "background-color: lightgrey">{{barang.harga_barang}}</th>
            <th style = "background-color: lightgrey">{{barang.deskripsi}}</th>
        </tr>
    {% endfor %}
    </table>
    ...<h5>Sesi terakhir login: {{ last_login }}</h5>
    
    <form id="form" onsubmit="return false">
        {% crsf_token %}
        <label>Nama Barang</label>
        <input type="text" name="nama_barang"></input>
        <label>Harga Barang</label>
        <input type="number" name="harga_barang"></input>
        <label>Deskripsi</label>
        <input type="text" name="deskripsi"></input>
        <button id="button" type="submit" value="Submit"></button>

    </form>
    <table id="table"></table>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  </body>
  <script>
    async function  getwishlist()
{
    return fetch("{% url 'get_wishlist_json'}").then((res) => res.json())

}
async function refreshwishlist()
{
    document.getElementById('table').innerHTML =" "
    const wishlist = await getwishlist()
    let htmlString = <tr>
        <th>Nama Barang</th>
        <th>Harga Barang</th>
        <th>Deskripsi</th>
        </tr>
        wishlist.forEach((item) => {
            htmlString +=  <tr>
                <th>$(item.fields.nama_barang)</th>
                <th>$(item.fields.harga_barang)</th>
                <th>$(item.fields.deskripsi)</th>
                </tr>
        })
        document.getElementById('table').innerHTML = htmlString

}
function addwishlist(){
    fetch("{% url 'add_wishlist_item' %}", {
        method: "POST",
        body: new FormData(document.querySelector('#form'))

    }).then(refreshwishlist)
    return false
}
  </script>
</html>